#!/usr/bin/python

import argparse

from fjd import Main


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Use FJDStart a worker process.')
    parser.add_argument('--exe', type=str, help="The path to executable script") 
    parser.add_argument('--instances', type=int, default=1,
                        help="Number of instances to start. The default is one. "\
                             "You can also list hosts in remote.conf.")
    parser.add_argument('--parameters', type=str, nargs='*',
                        help="List (comma-separated) of parameters to send to executable. "\
                             "Enclose several parameters per call like this: 'a b','c d'.")
    parser.add_argument('--project', type=str, help="Custom identifier (useful"\
                                  "when FJD is used to run several projects).")
    parser.add_argument('--curdir', type=str, help="Current directory workers should cd into before starting.")

    args = parser.parse_args()

    if args.parameters:
        params = [p.trim() for p in args.parameters.split(',')]
    else:
        params = []
    Main(exe=args.exe, instances=args.instances, parameters=params,
         project=args.project, curdir=args.curdir)

