#!/usr/bin/env python

import argparse
from fjd import Recruiter


if __name__ == '__main__':
    '''
    Start some workers on this PC
    '''
    parser = argparse.ArgumentParser(description='Recruit workers.')
    parser.add_argument('--project', type=str, help="Custom identifier (useful"\
                                  " when fjd is used to run several projects).")
    hf_parsers = parser.add_subparsers(title='action', dest='action')
    hp = hf_parsers.add_parser('hire', help='Hire some workers')
    hp.add_argument('num_workers', type=int, help="How many workers are needed.")
    fp = hf_parsers.add_parser('fire', help='Fire everyone (in this project)')

    args = parser.parse_args()

    if args.action == 'hire':
        recruiter = Recruiter(num_workers=args.num_workers, project=args.project)
        recruiter.hire()
    elif args.action == 'fire':
        recruiter = Recruiter(project=args.project)
        recruiter.fire()
        
