#!/usr/bin/env python

import sys
from fjd import Recruiter


if __name__ == '__main__':
    '''
    Start some workers on this PC
    ''' 
    a = sys.argv
    if not((len(a) in (3, 4) and a[1] == "hire")\
           or (len(a) in (2, 3) and a[1] == "fire")):
        print("[FJD] usage: fjd-recruiter {hire <num_workers>, fire} [working directory]")
        sys.exit(2)
    wdir = '~/.fjd'
    if a[1] == 'hire':
        if len(sys.argv) == 4:
            wdir = sys.argv[3]
        recruiter = Recruiter(num_workers = int(a[2]), wdir=wdir)
        recruiter.hire()
    elif a[1] == 'fire':
        if len(sys.argv) == 3:
            wdir = sys.argv[2]
        recruiter = Recruiter(wdir=wdir)
        recruiter.fire()
