#!/usr/bin/python

import sys
import argparse
from fjd import Worker


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Start a worker process.')
    parser.add_argument('--interval', type=int, default=5,
                        help="How often to poll for jobs.")
    parser.add_argument('--project', type=str, help="Custom identifier (useful"\
                                  " when fjd is used to run several projects).")
    args = parser.parse_args()
    Worker(project=args.project, interval=args.interval)
